compute_metrics:

  UK:
    Woke:
      min_cluster_size: 8
      min_samples: 4
      metric: euclidean
      cluster_selection_epsilon: 0.3
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 30
      n_components: 15
      min_dist: 0.3
      umap_metric: euclidean

    LGB:
      min_cluster_size: 8
      min_samples: 4
      metric: euclidean
      cluster_selection_epsilon: 0.5
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 50
      n_components: 15
      min_dist: 0.3
      umap_metric: euclidean

    Migration:
      min_cluster_size: 10
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.1
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 50
      n_components: 30
      min_dist: 0.09
      umap_metric: euclidean

  FR:
    Migration:
      min_cluster_size: 5
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.09
      cluster_selection_method: eom
      build_algo: auto
      n_neighbors: 20
      n_components: 10
      min_dist: 0.03
      umap_metric: euclidean

    Woke:
      min_cluster_size: 5
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.099
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 16
      n_components: 10
      min_dist: 0.03
      umap_metric: euclidean

    LGB:
      min_cluster_size: 5
      min_samples: 2
      metric: euclidean
      cluster_selection_epsilon: 0.099
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 16
      n_components: 10
      min_dist: 0.03
      umap_metric: euclidean

  SWE:
    Woke:
      min_cluster_size: 6
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.2
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 20
      n_components: 15
      min_dist: 0.09
      umap_metric: euclidean

    Migration:
      min_cluster_size: 6
      min_samples: 2
      metric: euclidean
      cluster_selection_epsilon: 0.4
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 30
      n_components: 20
      min_dist: 0.099
      umap_metric: euclidean

    LGB:
      min_cluster_size: 7
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.2
      cluster_selection_method: eom
      build_algo: auto
      n_neighbors: 40
      n_components: 30
      min_dist: 0.099
      umap_metric: euclidean

  IT:
    LGB:
      min_cluster_size: 10
      min_samples: 2
      metric: euclidean
      cluster_selection_epsilon: 0.4
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 30
      n_components: 20
      min_dist: 0.099
      umap_metric: euclidean

    Woke:
      min_cluster_size: 5
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.5
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 30
      n_components: 20
      min_dist: 0.09
      umap_metric: euclidean

    Migration:
      min_cluster_size: 5
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.5
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 30
      n_components: 20
      min_dist: 0.09
      umap_metric: euclidean

  RO:
    Migration:
      min_cluster_size: 10
      min_samples: 2
      metric: euclidean
      cluster_selection_epsilon: 0.5
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 30
      n_components: 20
      min_dist: 0.09
      umap_metric: euclidean

    LGB:
      min_cluster_size: 10
      min_samples: 2
      metric: euclidean
      cluster_selection_epsilon: 0.5
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 50
      n_components: 20
      min_dist: 0.099
      umap_metric: euclidean

    Woke:
      min_cluster_size: 8
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.35
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 50
      n_components: 20
      min_dist: 0.09
      umap_metric: euclidean

  HU:
    LGB:
      min_cluster_size: 15
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.3
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 50
      n_components: 20
      min_dist: 0.09
      umap_metric: euclidean

    Woke:
      min_cluster_size: 10
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.3
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 50
      n_components: 20
      min_dist: 0.09
      umap_metric: euclidean

    Migration:
      min_cluster_size: 7
      min_samples: 2
      metric: euclidean
      cluster_selection_epsilon: 0.05
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 50
      n_components: 25
      min_dist: 0.09
      umap_metric: euclidean

  ES:
    LGB:
      min_cluster_size: 12
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.15
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 40
      n_components: 30
      min_dist: 0.09
      umap_metric: euclidean

    Woke:
      min_cluster_size: 12
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.1
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 30
      n_components: 20
      min_dist: 0.09
      umap_metric: euclidean

    Migration:
      min_cluster_size: 15
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.0
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 35
      n_components: 20
      min_dist: 0.09
      umap_metric: euclidean

  DK:
    Woke:
      min_cluster_size: 6
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.1
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 40
      n_components: 25
      min_dist: 0.09
      umap_metric: euclidean

    LGB:
      min_cluster_size: 10
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.1
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 30
      n_components: 15
      min_dist: 0.09
      umap_metric: euclidean

    Migration:
      min_cluster_size: 6
      min_samples: 1
      metric: euclidean
      cluster_selection_epsilon: 0.2
      cluster_selection_method: leaf
      build_algo: auto
      n_neighbors: 30
      n_components: 20
      min_dist: 0.09
      umap_metric: euclidean